/* Copyright (C) 2006 Michael Voong

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. */

package data;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.Random;

public class PropertiesLoader {
    private static final String CONFIG_FILE = "colourmusic.properties";
    private Properties properties;

    public Properties getProperties() {
        return properties;
    }

    public PropertiesLoader() {
        properties = new Properties();
    }

    public void load() throws IOException {
        File file = new File(CONFIG_FILE);

        if (file.isFile()) {
            properties.load(new FileInputStream(file));
        } else {
            createNewFile();
        }
    }

    private void createNewFile() throws IOException {
        properties.setProperty("unique_id", Integer.toString(Math.abs(new Random().nextInt())));
        save();
    }

    public void save() throws IOException {

        properties
                .store(new FileOutputStream(CONFIG_FILE),
                        "Do not edit this file manually (unless you know what you're doing)");
    }

    public static void main(String[] args) {
        PropertiesLoader loader = new PropertiesLoader();
        try {
            loader.load();
        } catch (IOException e) {
            e.printStackTrace();

        }
    }

}
